### ISSUE TITLE
[MLV] crash when opening logfile

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/DebugTools#9]
Crash when opening a new rawlog file while already having a file open with active filters and active search.

```
2024-02-17 18:44:41,204 [DEBUG  ] LogViewer.utils.search {MainThread} search.py:91: Resetting start index to 14939RI on next search...
kf.kio.widgets.kdirmodel: No node found for item that was just removed: QUrl("file:///tmp/07t5Mb")
2024-02-17 18:44:48,876 [ERROR  ] LogViewer.ui.main_window {MainThread} exceptions.py:14: Exception in thread/pyqt callback!
Traceback (most recent call last):
  File "/home/thilo/cvs/DebugTools/src/shared/utils/exceptions.py", line 12, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thilo/cvs/DebugTools/src/LogViewer/ui/main_window.py", line 799, in _updateStatusbar
    len([item for item in self.rawlog if not item["uiItem"].isHidden()]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thilo/cvs/DebugTools/src/LogViewer/ui/main_window.py", line 799, in <listcomp>
    len([item for item in self.rawlog if not item["uiItem"].isHidden()]),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted
2024-02-17 18:44:48,912 [ERROR  ] LogViewer.ui.main_window {MainThread} exceptions.py:15: Shutting down immediately due to exception!
```

**Comment by tmolitor-stud-tu** [comment]
happened again:

```
2024-02-21 02:43:33,190 [ERROR  ] LogViewer.ui.main_window {MainThread} exceptions.py:14: Exception in thread/pyqt callback!
Traceback (most recent call last):
  File "/home/thilo/cvs/DebugTools/src/shared/utils/exceptions.py", line 12, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/thilo/cvs/DebugTools/src/LogViewer/ui/main_window.py", line 799, in _updateStatusbar
    len([item for item in self.rawlog if not item["uiItem"].isHidden()]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thilo/cvs/DebugTools/src/LogViewer/ui/main_window.py", line 799, in <listcomp>
    len([item for item in self.rawlog if not item["uiItem"].isHidden()]),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type QListWidgetItem has been deleted
2024-02-21 02:43:33,224 [ERROR  ] LogViewer.ui.main_window {MainThread} exceptions.py:15: Shutting down immediately due to exception!
```
